Repository no-salty-eating/backend, pull requests merged in 2025-01, with the labels that each got.

#10 #2 feat: product init setting
  product/.env
  product/.gitattributes
  product/.gitignore
  product/build.gradle
  product/gradle/wrapper/gradle-wrapper.jar
  product/gradle/wrapper/gradle-wrapper.properties
  product/gradlew
  product/gradlew.bat
  product/settings.gradle
  product/src/main/java/com/sparta/product/ProductApplication.java
  product/src/main/java/com/sparta/product/application/dtos/Response.java
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductRequestDto.java
  product/src/main/java/com/sparta/product/domain/common/BaseEntity.java
  product/src/main/java/com/sparta/product/domain/core/Category.java
  product/src/main/java/com/sparta/product/domain/core/Product.java
  product/src/main/java/com/sparta/product/domain/core/ProductCategory.java
  product/src/main/java/com/sparta/product/domain/core/TimeSaleProduct.java
  product/src/main/java/com/sparta/product/domain/core/TimeSaleSoldOut.java
  product/src/main/java/com/sparta/product/infrastructure/config/KafkaConfig.java
  product/src/main/java/com/sparta/product/infrastructure/config/QueryDslConfig.java
  product/src/main/java/com/sparta/product/presentation/exception/CustomException.java
  product/src/main/java/com/sparta/product/presentation/exception/Error.java
  product/src/main/java/com/sparta/product/presentation/exception/NotFoundMemberException.java
  product/src/main/java/com/sparta/product/presentation/exception/NotFoundProductException.java
  product/src/main/java/com/sparta/product/presentation/exception/handler/CommonExceptionHandler.java
  product/src/main/resources/application.yml
  product/src/test/java/com/sparta/product/ProductApplicationTests.java
Labels: enhancement

#11 [refactor] #2: 리뷰 내용 바탕으로 코드 리팩토링
  .env
  product/.gitignore
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/productCategory/ProductCategoryRequestDto.java
  product/src/main/java/com/sparta/product/application/exception/Error.java
  product/src/main/java/com/sparta/product/application/exception/NotFoundProductException.java
  product/src/main/java/com/sparta/product/application/exception/ProductException.java
  product/src/main/java/com/sparta/product/application/exception/handler/CommonExceptionHandler.java
  product/src/main/java/com/sparta/product/domain/core/Category.java
  product/src/main/java/com/sparta/product/domain/core/Product.java
  product/src/main/java/com/sparta/product/domain/core/ProductCategory.java
  product/src/main/java/com/sparta/product/domain/core/TimeSaleProduct.java
  product/src/main/java/com/sparta/product/domain/core/TimeSaleSoldOut.java
  product/src/main/java/com/sparta/product/presentation/exception/NotFoundMemberException.java
  product/src/main/resources/application-local.yml
Labels: refactor

#21 [feature] #12, #16, #18, #20 : 카테고리 생성, 상품 생성, 상품 단건 조회, 상품 변경 API
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductResponseDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductUpdateRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/productCategory/ProductCategoryResponseDto.java
  product/src/main/java/com/sparta/product/application/exception/category/AlreadyExistCategoryException.java
  product/src/main/java/com/sparta/product/application/exception/category/CategoryException.java
  product/src/main/java/com/sparta/product/application/exception/category/NotFoundCategoryException.java
  product/src/main/java/com/sparta/product/application/exception/common/Error.java
  product/src/main/java/com/sparta/product/application/exception/common/ForbiddenException.java
  product/src/main/java/com/sparta/product/application/exception/common/ForbiddenRoleException.java
  product/src/main/java/com/sparta/product/application/exception/handler/CommonExceptionHandler.java
  product/src/main/java/com/sparta/product/application/exception/product/NotFoundProductException.java
  product/src/main/java/com/sparta/product/application/exception/product/ProductException.java
  product/src/main/java/com/sparta/product/application/service/CategoryService.java
  product/src/main/java/com/sparta/product/application/service/ProductService.java
  product/src/main/java/com/sparta/product/domain/common/BaseEntity.java
  product/src/main/java/com/sparta/product/domain/common/UserRoleEnum.java
  product/src/main/java/com/sparta/product/domain/core/Category.java
  product/src/main/java/com/sparta/product/domain/core/Product.java
  product/src/main/java/com/sparta/product/domain/repository/CategoryRepository.java
  product/src/main/java/com/sparta/product/domain/repository/ProductRepository.java
  product/src/main/java/com/sparta/product/infrastructure/repository/CategoryRepositoryImpl.java
  product/src/main/java/com/sparta/product/infrastructure/repository/CustomCategoryRepository.java
  product/src/main/java/com/sparta/product/infrastructure/repository/CustomProductRepository.java
  product/src/main/java/com/sparta/product/infrastructure/repository/ProductRepositoryImpl.java
  product/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  product/src/main/java/com/sparta/product/presentation/controller/ProductController.java
Labels: feat

#24 [feature] #23: 상품 삭제 API
  product/src/main/java/com/sparta/product/application/service/ProductService.java
  product/src/main/java/com/sparta/product/presentation/controller/ProductController.java
Labels: feat

#25 [refactor] #23: productUpdate 메서드 refactor
  product/src/main/java/com/sparta/product/application/service/ProductService.java
  product/src/main/java/com/sparta/product/domain/core/Product.java
Labels: refactor

#27 [feature] #26: 카테고리 단건 조회, 수정, 삭제 API
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryResponseDto.java
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryUpdateRequestDto.java
  product/src/main/java/com/sparta/product/application/service/CategoryService.java
  product/src/main/java/com/sparta/product/domain/core/Category.java
  product/src/main/java/com/sparta/product/domain/repository/CategoryRepository.java
  product/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
Labels: feat

#32 feat : gateway Authentication 설정
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  gateway/src/main/java/com/sparta/gateway/GatewayApplication.java
  gateway/src/main/java/com/sparta/gateway/infrastructure/filter/LocalJwtAuthenticationFilter.java
  gateway/src/main/java/com/sparta/gateway/infrastructure/util/JwtUtil.java
  gateway/src/main/resources/application.yml
  gateway/src/test/java/com/sparta/gateway/GatewayApplicationTests.java
Labels: feat

#34 feat : user login 기능과 crud 생성
  user/.gitattributes
  user/.gitignore
  user/build.gradle
  user/gradle/wrapper/gradle-wrapper.jar
  user/gradle/wrapper/gradle-wrapper.properties
  user/gradlew
  user/gradlew.bat
  user/settings.gradle
  user/src/main/java/com/sparta/user/UserApplication.java
  user/src/main/java/com/sparta/user/application/dto/Response.java
  user/src/main/java/com/sparta/user/application/dto/request/LogInRequestDto.java
  user/src/main/java/com/sparta/user/application/dto/request/SignInRequestDto.java
  user/src/main/java/com/sparta/user/application/dto/request/UpdateUserRequestDto.java
  user/src/main/java/com/sparta/user/application/dto/response/JwtTokenResponseDto.java
  user/src/main/java/com/sparta/user/application/dto/response/LoginIdResponseDto.java
  user/src/main/java/com/sparta/user/application/dto/response/UserResponseDto.java
  user/src/main/java/com/sparta/user/application/exception/Error.java
  user/src/main/java/com/sparta/user/application/exception/UserException.java
  user/src/main/java/com/sparta/user/application/service/AuthService.java
  user/src/main/java/com/sparta/user/application/service/UserService.java
  user/src/main/java/com/sparta/user/domain/model/UserRoleEnum.java
  user/src/main/java/com/sparta/user/domain/model/common/BaseEntity.java
  user/src/main/java/com/sparta/user/domain/model/core/User.java
  user/src/main/java/com/sparta/user/infrastructure/config/JpaConfig.java
  user/src/main/java/com/sparta/user/infrastructure/config/SwaggerConfig.java
  user/src/main/java/com/sparta/user/infrastructure/config/WebConfig.java
  user/src/main/java/com/sparta/user/infrastructure/repository/UserRepository.java
  user/src/main/java/com/sparta/user/infrastructure/util/JwtUtil.java
  user/src/main/java/com/sparta/user/presentation/controller/AuthController.java
  user/src/main/java/com/sparta/user/presentation/controller/UserController.java
  user/src/main/java/com/sparta/user/presentation/controller/handler/CommonExceptionHandler.java
  user/src/main/resources/application-dev.yml
  user/src/main/resources/application.yml
  user/src/test/java/com/sparta/user/UserApplicationTests.java
Labels: feat

#38 [#30] feat : order create api
  order/build.gradle.kts
  order/src/main/kotlin/com/study/order/OrderApplication.kt
  order/src/main/kotlin/com/study/order/application/client/CouponService.kt
  order/src/main/kotlin/com/study/order/application/client/PointService.kt
  order/src/main/kotlin/com/study/order/application/client/ProductService.kt
  order/src/main/kotlin/com/study/order/application/dto/event/PaymentEvent.kt
  order/src/main/kotlin/com/study/order/application/dto/event/ProductStockDecreaseEvent.kt
  order/src/main/kotlin/com/study/order/application/dto/response/CategoryResponse.kt
  order/src/main/kotlin/com/study/order/application/dto/response/CouponResponse.kt
  order/src/main/kotlin/com/study/order/application/dto/response/ProductResponse.kt
  order/src/main/kotlin/com/study/order/application/exception/CouponException.kt
  order/src/main/kotlin/com/study/order/application/exception/Error.kt
  order/src/main/kotlin/com/study/order/application/exception/PointException.kt
  order/src/main/kotlin/com/study/order/application/exception/ProductException.kt
  order/src/main/kotlin/com/study/order/application/messaging/MessageService.kt
  order/src/main/kotlin/com/study/order/application/service/OrderService.kt
  order/src/main/kotlin/com/study/order/domain/model/OrderDetail.kt
  order/src/main/kotlin/com/study/order/domain/repository/OrderDetailRepository.kt
  order/src/main/kotlin/com/study/order/domain/repository/OrderRepository.kt
  order/src/main/kotlin/com/study/order/infrastructure/client/CouponService.kt
  order/src/main/kotlin/com/study/order/infrastructure/client/PointService.kt
  order/src/main/kotlin/com/study/order/infrastructure/client/ProductService.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/kafka/ReactiveKafkaInitializer.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/log/AspectConfig.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/log/ErrorConfig.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/log/LoggerProvider.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/log/MdcFilter.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/log/RequestLoggingFilter.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/webClient/WebClientConfig.kt
  order/src/main/kotlin/com/study/order/infrastructure/messaging/provider/KafkaMessageProducer.kt
  order/src/main/kotlin/com/study/order/infrastructure/repository/OrderDetailRepository.kt
  order/src/main/kotlin/com/study/order/presentation/api/controller/OrderController.kt
  order/src/main/kotlin/com/study/order/presentation/api/controller/docs/OrderControllerDocs.kt
  order/src/main/kotlin/com/study/order/presentation/api/handler/GlobalExceptionHandler.kt
  order/src/main/kotlin/com/study/order/presentation/api/request/CreateOrderRequest.kt
  order/src/main/kotlin/com/study/order/presentation/api/request/ProductQuantityRequest.kt
  order/src/main/resources/application-dev.yml
  order/src/main/resources/application-test.yml
  order/src/main/resources/db-init/schema.sql
  order/src/test/kotlin/com/study/order/application/service/OrderServiceTest.kt
  server/.gitattributes
  server/.gitignore
  server/build.gradle.kts
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle.kts
  server/src/main/kotlin/com/study/server/ServerApplication.kt
  server/src/main/resources/application.yml
  server/src/test/kotlin/com/study/server/ServerApplicationTests.kt
  server/src/test/kotlin/com/study/server/test.http
Labels: feat

#41 refactor : product 코드 수정
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryResponseDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductResponseDto.java
  product/src/main/java/com/sparta/product/application/dtos/productCategory/ProductCategoryResponseDto.java
  product/src/main/java/com/sparta/product/application/dtos/timesale/TimeSaleProductRequestDto.java
  product/src/main/java/com/sparta/product/application/exception/common/Error.java
  product/src/main/java/com/sparta/product/application/exception/productCategory/NotFoundProductCategoryException.java
  product/src/main/java/com/sparta/product/application/exception/productCategory/ProductCategoryException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/TimeSaleException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/TimeSaleQuantityExceedProductStockException.java
  product/src/main/java/com/sparta/product/application/service/CategoryService.java
  product/src/main/java/com/sparta/product/application/service/ProductService.java
  product/src/main/java/com/sparta/product/application/service/TimeSaleProductService.java
  product/src/main/java/com/sparta/product/application/service/TimeSaleRedisManager.java
  product/src/main/java/com/sparta/product/domain/core/Category.java
  product/src/main/java/com/sparta/product/domain/core/Product.java
  product/src/main/java/com/sparta/product/domain/core/ProductCategory.java
  product/src/main/java/com/sparta/product/domain/core/TimeSaleProduct.java
  product/src/main/java/com/sparta/product/domain/repository/CategoryRepository.java
  product/src/main/java/com/sparta/product/domain/repository/ProductCategoryRepository.java
  product/src/main/java/com/sparta/product/domain/repository/ProductRepository.java
  product/src/main/java/com/sparta/product/domain/repository/TimeSaleProductRepository.java
  product/src/main/java/com/sparta/product/infrastructure/config/RedisConfig.java
  product/src/main/java/com/sparta/product/infrastructure/repository/CustomTimeSaleProductRepository.java
  product/src/main/java/com/sparta/product/infrastructure/repository/TimeSaleProductRepositoryImpl.java
  product/src/main/java/com/sparta/product/presentation/Response.java
  product/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  product/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  product/src/main/java/com/sparta/product/presentation/handler/CommonExceptionHandler.java
  product/src/main/resources/application.yml
Labels: refactor

#50 refactor : Error Convention에 따라 gateway 리팩토링
  gateway/src/main/java/com/sparta/gateway/application/exception/Error.java
  gateway/src/main/resources/application.yml
Labels: refactor

#51 refactor : Error Convention에 따라 user 리팩토링
  user/src/main/java/com/sparta/user/application/exception/Error.java
  user/src/main/java/com/sparta/user/application/service/AuthService.java
  user/src/main/java/com/sparta/user/presentation/controller/handler/CommonExceptionHandler.java
  user/src/main/java/com/sparta/user/presentation/handler/CommonExceptionHandler.java
  user/src/main/resources/application.yml
Labels: refactor

#53 refactor #48 : product service 리뷰 바탕으로 코드 수정
  product/src/main/java/com/sparta/product/application/dtos/Response.java
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryResponseDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductResponseDto.java
  product/src/main/java/com/sparta/product/application/exception/category/AlreadyExistCategoryException.java
  product/src/main/java/com/sparta/product/application/exception/category/NotFoundCategoryException.java
  product/src/main/java/com/sparta/product/application/exception/common/Error.java
  product/src/main/java/com/sparta/product/application/exception/common/ForbiddenRoleException.java
  product/src/main/java/com/sparta/product/application/exception/product/NotFoundProductException.java
  product/src/main/java/com/sparta/product/application/exception/productCategory/NotFoundProductCategoryException.java
  product/src/main/java/com/sparta/product/application/exception/scheduler/TimeSaleScheduleException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/ExceedTimeSaleQuantityException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/InvalidTimeSaleEndTimeException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/InvalidTimeSaleStartTimeException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/NotFoundOnTimeSaleException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/NotFoundTimeSaleException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/TimeSaleQuantityExceedProductStockException.java
  product/src/main/java/com/sparta/product/application/service/CategoryService.java
  product/src/main/java/com/sparta/product/application/service/ProductService.java
  product/src/main/java/com/sparta/product/application/service/TimeSaleService.java
  product/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  product/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  product/src/main/java/com/sparta/product/presentation/controller/TimeSaleController.java
  product/src/main/java/com/sparta/product/presentation/handler/CommonExceptionHandler.java
Labels: refactor

#67 feat #55: 상품, 타임세일 상품 재고 감소
  product/src/main/java/com/sparta/product/application/dtos/category/CategoryResponseDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductPurchaseRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/product/ProductResponseDto.java
  product/src/main/java/com/sparta/product/application/dtos/timesale/TimeSaleProductPurchaseRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/timesale/TimeSaleProductRequestDto.java
  product/src/main/java/com/sparta/product/application/dtos/timesale/TimeSaleProductResponseDto.java
  product/src/main/java/com/sparta/product/application/exception/common/Error.java
  product/src/main/java/com/sparta/product/application/exception/timesale/EmptyStockException.java
  product/src/main/java/com/sparta/product/application/scheduler/TimeSaleSchedulerService.java
  product/src/main/java/com/sparta/product/application/scheduler/redis/RedisKeys.java
  product/src/main/java/com/sparta/product/application/scheduler/redis/TimeSaleRedisManager.java
  product/src/main/java/com/sparta/product/application/scheduler/redis/TimeSaleScheduler.java
  product/src/main/java/com/sparta/product/application/service/CategoryService.java
  product/src/main/java/com/sparta/product/application/service/ProductService.java
  product/src/main/java/com/sparta/product/application/service/TimeSaleService.java
  product/src/main/java/com/sparta/product/domain/common/BaseEntity.java
  product/src/main/java/com/sparta/product/domain/core/Product.java
  product/src/main/java/com/sparta/product/domain/core/TimeSaleProduct.java
  product/src/main/java/com/sparta/product/domain/repository/TimeSaleProductRepository.java
  product/src/main/java/com/sparta/product/infrastructure/config/CacheConfig.java
  product/src/main/java/com/sparta/product/infrastructure/config/JacksonConfig.java
  product/src/main/java/com/sparta/product/infrastructure/config/KafkaConfig.java
  product/src/main/java/com/sparta/product/infrastructure/config/RedisConfig.java
  product/src/main/java/com/sparta/product/infrastructure/dtos/ProductInternalResponseDto.java
  product/src/main/java/com/sparta/product/infrastructure/kafka/event/StockDecreaseMessage.java
  product/src/main/java/com/sparta/product/infrastructure/kafka/kafkaConsumer.java
  product/src/main/java/com/sparta/product/presentation/Response.java
  product/src/main/java/com/sparta/product/presentation/controller/CategoryController.java
  product/src/main/java/com/sparta/product/presentation/controller/ProductController.java
  product/src/main/java/com/sparta/product/presentation/controller/TimeSaleController.java
  product/src/main/java/com/sparta/product/presentation/handler/CommonExceptionHandler.java
  product/src/main/resources/application-local.yml
Labels: feat

#74 [#73] feat : Order RedLock
  order/build.gradle.kts
  order/src/main/kotlin/com/study/order/application/dto/event/provider/ProductStockAdjustmentEvent.kt
  order/src/main/kotlin/com/study/order/application/dto/response/ProductResponseDto.kt
  order/src/main/kotlin/com/study/order/application/exception/Error.kt
  order/src/main/kotlin/com/study/order/application/exception/RedisException.kt
  order/src/main/kotlin/com/study/order/application/service/CacheService.kt
  order/src/main/kotlin/com/study/order/application/service/OrderService.kt
  order/src/main/kotlin/com/study/order/domain/model/Order.kt
  order/src/main/kotlin/com/study/order/infrastructure/cache/CacheService.kt
  order/src/main/kotlin/com/study/order/infrastructure/cache/RedisService.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/log/ErrorConfig.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/log/MdcFilter.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/redis/RedisConfig.kt
  order/src/main/kotlin/com/study/order/infrastructure/utils/QueryExtension.kt
  order/src/main/kotlin/com/study/order/infrastructure/utils/ServletHttpRequestExtension.kt
  order/src/main/kotlin/com/study/order/infrastructure/utils/TransactionHelper.kt
  order/src/main/kotlin/com/study/order/presentation/api/handler/GlobalExceptionHandler.kt
  payment/src/main/kotlin/com/study/payment/infrastructure/utils/TransactionHelper.kt
Labels: feat

#77 [feature] #55: 상품 재고 차감 API
  product/src/main/java/com/sparta/product/application/dtos/product/ProductResponseDto.java
  product/src/main/java/com/sparta/product/application/exception/common/Error.java
  product/src/main/java/com/sparta/product/application/exception/product/NotEnoughProductStockException.java
  product/src/main/java/com/sparta/product/application/exception/product/NotFoundProductInRedisException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/NotEnoughTimeSaleStockInDbException.java
  product/src/main/java/com/sparta/product/application/exception/timesale/NotFoundTimeSaleInRedisException.java
  product/src/main/java/com/sparta/product/application/scheduler/TimeSaleSchedulerService.java
  product/src/main/java/com/sparta/product/application/scheduler/redis/RedisKeys.java
  product/src/main/java/com/sparta/product/application/scheduler/redis/RedisManager.java
  product/src/main/java/com/sparta/product/application/scheduler/redis/TimeSaleScheduler.java
  product/src/main/java/com/sparta/product/application/service/ProductService.java
  product/src/main/java/com/sparta/product/application/service/TimeSaleService.java
  product/src/main/java/com/sparta/product/domain/core/Product.java
  product/src/main/java/com/sparta/product/domain/core/TimeSaleProduct.java
  product/src/main/java/com/sparta/product/infrastructure/kafka/event/StockDecreaseMessage.java
  product/src/main/java/com/sparta/product/infrastructure/kafka/kafkaConsumer.java
  product/src/main/java/com/sparta/product/presentation/controller/ProductController.java
Labels: feat

#92 feat : Cicd
  .github/deploy-ecr.yml
Labels: feat

#97 [refactor] : ROLE_ 붙여서 권한 가져오도록 수정.
  product/src/main/java/com/sparta/product/application/service/CategoryService.java
  product/src/main/java/com/sparta/product/application/service/ProductService.java
  product/src/main/java/com/sparta/product/application/service/TimeSaleService.java
Labels: refactor

#103 [refactor] : db 감소만 되도록 메소드 수정
  product/src/main/java/com/sparta/product/application/service/ProductService.java
Labels: refactor

#109 Feature/108 order payment test
  .github/workflows/aws.yml
  coupon/build.gradle
  coupon/src/main/java/com/sparta/coupon/application/dto/request/CreateCouponRequestDto.java
  coupon/src/main/java/com/sparta/coupon/application/exception/Error.java
  coupon/src/main/java/com/sparta/coupon/application/service/CouponService.java
  coupon/src/main/java/com/sparta/coupon/domain/core/Coupon.java
  coupon/src/main/java/com/sparta/coupon/infrastructure/config/RedisConfig.java
  coupon/src/main/java/com/sparta/coupon/infrastructure/kafka/event/OrderSuccessEvent.java
  coupon/src/main/java/com/sparta/coupon/infrastructure/kafka/event/UseCouponMessage.java
  coupon/src/main/java/com/sparta/coupon/infrastructure/kafka/kafkaConsumer.java
  coupon/src/main/java/com/sparta/coupon/presentation/controller/CouponController.java
  gateway/build.gradle
  order/src/main/kotlin/com/study/order/application/client/PaymentService.kt
  order/src/main/kotlin/com/study/order/application/exception/CouponException.kt
  order/src/main/kotlin/com/study/order/application/exception/Error.kt
  order/src/main/kotlin/com/study/order/application/exception/OrderException.kt
  order/src/main/kotlin/com/study/order/application/exception/ProductException.kt
  order/src/main/kotlin/com/study/order/application/exception/RedisException.kt
  order/src/main/kotlin/com/study/order/application/service/CacheService.kt
  order/src/main/kotlin/com/study/order/application/service/OrderService.kt
  order/src/main/kotlin/com/study/order/application/service/OrderTestService.kt
  order/src/main/kotlin/com/study/order/domain/model/OrderStatus.kt
  order/src/main/kotlin/com/study/order/infrastructure/cache/RedisService.kt
  order/src/main/kotlin/com/study/order/infrastructure/client/PaymentService.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/kafka/KafkaConfig.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/log/MdcFilter.kt
  order/src/main/kotlin/com/study/order/infrastructure/config/webClient/WebClientConfig.kt
  order/src/main/kotlin/com/study/order/infrastructure/messaging/consumer/PaymentEventListener.kt
  order/src/main/kotlin/com/study/order/presentation/api/controller/OrderController.kt
  order/src/main/kotlin/com/study/order/presentation/api/controller/docs/OrderControllerDocs.kt
  order/src/main/kotlin/com/study/order/presentation/api/handler/GlobalExceptionHandler.kt
  order/src/main/kotlin/com/study/order/presentation/api/request/CreateOrderRequest.kt
  order/src/main/kotlin/com/study/order/presentation/api/request/ProductQuantityRequest.kt
  order/src/main/resources/application-dev.yml
  order/src/main/resources/application.yml
  payment/src/main/kotlin/com/study/payment/application/service/PaymentService.kt
  payment/src/main/kotlin/com/study/payment/application/service/PaymentTestService.kt
  payment/src/main/kotlin/com/study/payment/infrastructure/config/kafka/KafkaConfig.kt
  payment/src/main/kotlin/com/study/payment/infrastructure/messaging/comsumer/OrderEventListener.kt
  payment/src/main/kotlin/com/study/payment/presentation/api/controller/PaymentRestController.kt
  product/build.gradle
  product/src/main/java/com/sparta/product/infrastructure/kafka/event/OrderSuccessMessage.java
  user/build.gradle
Labels: feat
